### ISSUE TITLE
Trend images are broken for longer time ranges

### ISSUE THREAD

**Issue by worenga** [HTTPArchive/httparchive#121]
Hi,

i wanted to get the total transfer size trend image from here:

http://httparchive.org/trends.php?s=All&minlabel=Nov+15+2010&maxlabel=May+15+2016#numurls

Choosing the date range Nov 15 2010 -> May 15 2016 shows the diagram correctly,
however expanding it further e.g. to Juni 1 2016 lets the diagram not show 

c.f., 
http://httparchive.org/trends.php?s=All&minlabel=Nov+15+2010&maxlabel=Jun+1+2016#numurls

it seems there are other images affected as well.

**Comment by rviscomi** [comment]
Yeah, that's odd. At a glance the Google Charts API requests are failing with `400 (Bad Request)` responses.

We plan to replace Google Charts with Highcharts in v2, so this won't be an issue.

**Comment by worenga** [comment]
Meanwhile is there a way to manually get the query that computes this chart?

**Comment by Themanwithoutaplan** [comment]
@worenga if you just want the queries then should be able to get them from my port (which uses the more modern version of Google's charting API) https://bitbucket.org/charlie_x/python-httparchive/src/018b26de63ca1b8329cb5f994763d39d7cb68f17/httparchive/views/trends.py?at=default&fileviewer=file-view-default

Unfortunately, there's a problem on my server otherwise you could just look at the charts there. PM me if you've got questions about this.

**Comment by rviscomi** [comment]
Would it suffice to adjust the time window slightly? For example, shifting the start date by one crawl produces a valid image: http://httparchive.org/trends.php?s=All&minlabel=Nov+29+2010&maxlabel=Jun+1+2016#numurls

If not, the query would be a bit tricky since it spans multiple dated tables but I'd be happy to assist.

**Comment by worenga** [comment]
Thanks, i've ended up grabbing the raw data from the URL and making my own plot script for it.

**Comment by rviscomi** [comment]
Ok great!
