### ISSUE TITLE
New report: Loading metrics

### ISSUE THREAD

**Issue by addyosmani** [HTTPArchive/httparchive#125]
**Metrics:** 
First Meaningful Paint, Time-to-first-Interactive, Time-to-consistently-interactive

**Source:** WebPageTest Lighthouse reports

**Visualization:** time-series charts similar to http://beta.httparchive.org/reports/js

**URL:** http://beta.httparchive.org/reports/loading

From @igrigorik 

> We'd also want a companion "deep-dive" report for each individual run, with full histograms for each metric, etc.

**Comment by rviscomi** [comment]
Example query to get desired metrics:

```sql
SELECT
  JSON_EXTRACT(report, "$.audits.consistently-interactive.rawValue") AS ttci,
  JSON_EXTRACT(report, "$.audits.first-interactive.rawValue") AS ttfi,
  JSON_EXTRACT(report, "$.audits.first-meaningful-paint.rawValue") AS fmp
FROM
  [httparchive:har.latest_lighthouse_mobile]
```

**Comment by rviscomi** [comment]
Progress on this:

http://beta.httparchive.org/reports/loading?start=latest
![loadingreport](https://user-images.githubusercontent.com/1120896/30459675-1d6878a4-9980-11e7-9011-97d694751d26.png)

http://beta.httparchive.org/reports/loading
![loadingtimeseries](https://user-images.githubusercontent.com/1120896/30459702-3fe77a1a-9980-11e7-96ca-3f87e316c04a.png)

**Comment by rviscomi** [comment]
Implementation notes...

I really wanted to write the histogram queries to use a table wildcard, eg `har.*`, but it just wouldn't work because of how heterogeneous the har dataset is. See https://github.com/HTTPArchive/httparchive/issues/112 for prior discussion on this issue. As a workaround, I created a new [lighthouse](https://bigquery.cloud.google.com/dataset/httparchive:lighthouse) dataset that duplicates all of the LH tables that are in har. The dataflow pipeline isn't updated to write to both places, this was more of a proof of concept. I'm in favor of more homogeneous datasets like this to make querying easier, so I think it would be a good change to redirect the LH output solely to the lighthouse dataset.

**Comment by rviscomi** [comment]
Closing this now that the report is up and running: https://beta.httparchive.org/reports/loading-speed
