### ISSUE TITLE
Chromium UseCounter data is mislabeled?

### ISSUE THREAD

**Issue by mikewest** [HTTPArchive/httparchive#147]
In the 2018-02-01 run, the use counter data looks like it's stopped getting new names for the feature labels. That is, `CrossOriginWorkerTextHtml` is feature 2184, but it's listed as `Feature_2184` in the table. The following query returns no results:

```
SELECT 
  url,
  JSON_EXTRACT(payload, '$._blinkFeatureFirstUsed.Features.Feature_2184') AS feature
FROM [httparchive:har.2018_02_01_chrome_pages]
HAVING feature IS NOT NULL
ORDER BY url
```

While the following returns 5 entries:

```
SELECT 
  url,
  JSON_EXTRACT(payload, '$._blinkFeatureFirstUsed.Features.Feature_2184') AS feature
FROM [httparchive:har.2018_02_01_chrome_pages]
HAVING feature IS NOT NULL
ORDER BY url
```

**Comment by pmeenan** [comment]
The labels are updated manually and it had been a while since I last did it.  I [updated them on Feb 14](https://github.com/WPO-Foundation/trace-parser/commit/96c5bb233f3b443eb36338f52cb14a0408d9de58) when the certificate information was added.  The Feb 15 crawl should have it with the correct name.

I'll set up a recurring calendar reminder every 6 weeks to make sure I freshen the list (should be frequent enough since we test against stable and the feature names will be there well before launch).

**Comment by mikewest** [comment]
Got it. Thanks!

(Can I assume that the Feb 15th crawl will show up in the vaguely near future? :) )

**Comment by pmeenan** [comment]
@rviscomi do you happen to know if the Feb 15 and March 1 crawls got wedged in HAR processing?  It should have long-since been available.  The requests and pages tables are already there as are the response bodies tables.

Did the HAR data move out from the "har" table into the "pages", "requests" and "response_bodies" tables instead (which look to be json carve-outs from the full HAR's).

It looks like the feature data is available in the pages json data which should be MUCH cheaper to query than the full HAR's.  Looks like they are labeled as _desktop and _mobile (i.e. httparchive:pages.2018_03_01_desktop)

https://bigquery.cloud.google.com/table/httparchive:pages.2018_03_01_desktop?pli=1&tab=preview

**Comment by pmeenan** [comment]
Guess that would be a yes on the re-organizing: https://discuss.httparchive.org/t/notice-reorganizing-the-har-and-runs-datasets-on-bigquery/1235

We probably need an announcements section or something on the main HTTP Archive page or the ability to pin them in the discuss group so they stay front-and-center.

**Comment by rviscomi** [comment]
Yes sorry for the confusion; the datasets have been reorganized.

FWIW I'm still seeing 0 results for this particular feature ID, not sure if it should be included now after the Feb 14 changes or if it's only available under a different name.

```sql
#standardSQL
SELECT
  COUNT(JSON_EXTRACT(payload, '$._blinkFeatureFirstUsed.Features.Feature_2184')) AS feature
FROM
  `httparchive.pages.2018_03_01_desktop`
HAVING
  feature IS NOT NULL
```

**Comment by pmeenan** [comment]
After Feb 14 it is by the real name, not the ID - Features.CrossOriginWorkerTextHtml

**Comment by rviscomi** [comment]
Ah ok thanks. Seeing 6 hits for it now, which seems very low but maybe expected.

**Comment by pmeenan** [comment]
New feature presumably and 5 hits on Feb 1 so yeah, sounds about right.

**Comment by mikewest** [comment]
Thanks to you both for helping me find the new location! In this case, I'm very happy that the use counter is low, because it's something I'm trying to deprecate/remove. :)

Is there somewhere I should be paying attention to for these kinds of changes in the future? I tend to use HTTPArchive in spurts, and must have missed the announcement.

**Comment by rviscomi** [comment]
> Is there somewhere I should be paying attention to for these kinds of changes in the future?

This change was announced on the [HTTP Archive Slack channel](http://bit.ly/http-archive-slack) and the [discuss.httparchive.org](discuss.httparchive.org) forum, although at the time it wasn't pinned to the top.
