### ISSUE TITLE
Comparing Web Fonts Requests From Outside Font Services versus Requests For Web Fonts Self Hosted

### ISSUE THREAD

**Issue by richardfink** [HTTPArchive/httparchive#65]
I would like a chart showing, out of the number of sites using web fonts, how many are making the requests from outside services like Google Fonts, and how many are self-hosting the fonts.

**Comment by stevesouders** [comment]
This is a niche metric, so it's probably not worth taking up real estate in the UI and resources for storing the data. Also, it's hard to define "outside services", especially since those can change over time. 

I recommend trying to answer this question in Big Query. If the results look valid & interesting, share your query and results at https://discuss.httparchive.org/ for further discussion.

**Comment by richardfink** [comment]
Thank you for the quick reply Steve.

I'm an admirer of your work, btw. Didn't know you were involved in the
project, quite frankly.

I wish more sites took your advice on optimization.

I'll try a query first.

Rich

https://richardfink.github.io/rfink/bio.htm
