### ISSUE TITLE
Mobile website HTTP request's count has a weird increase since 2016.02.15

### ISSUE THREAD

**Issue by Handsome2734** [HTTPArchive/httparchive#67]
http://mobile.httparchive.org/trends.php?s=All&minlabel=May+15+2015&maxlabel=May+1+2016#bytesTotal&reqTotal
Before 2016.02.15, request's total count keeps between 60~80. But it suddenly increases to 100+ after 2016.02.15.
I'd like to know whether this is a data error, or just something happened that caused this weird increase.

**Comment by pmeenan** [comment]
Should be a blog post and announcement about it early next week but the jump is from switching from iPhone/iOS 4 to Android/Chrome (current stable).  iOS 4 was so ancient that a lot of sites were no longer actually serving content to it and were showing a "not supported" interstitial instead.

**Comment by Handsome2734** [comment]
Looking forward to the blog post :)

**Comment by nhoizey** [comment]
The blog post is there:
http://www.stevesouders.com/blog/2016/05/23/http-archive-switches-to-chrome/

It doesn't mention anything about this big increase, unfortunately.

https://twitter.com/nhoizey/status/735052038099374080

**Comment by stevesouders** [comment]
We believe the data is valid. There were some differences we noticed that were inaccurate because of doing emulation - eg, the emulator does NOT look for touch icons. However, these were small differences. We'd love it if the community would dig into the data and see if the other changes are valid (eg, android websites are simply bigger than iphone) or buggy.
